# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
paginate_path: "blog/page:num/"
language: 'en'
words_per_minute: 200

url: https://www.andredsm.com/

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# the subaddress to the index of the blog
blogurl: /blog

# Website info
title: Ordered Bits
description: Daydreams about data, programming and graphics-related topics
cover: assets/theme/images/blog-cover.jpg
logo: assets/theme/images/blog-icon.png
logo_dark: assets/theme/images/favicon.png
favicon: assets/theme/images/favicon.png
CNAME: www.andredsm.com

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: andredsm
# facebook: ghost
github: andredsm
linkedin: andredsm
email: andremoreira.cp@gmail.com

# Disqus
disqus: True
disqus_shortname: andredsm # replace with your disqus username

# Google Analytics
google_analytics: UA-50931414-1 # replace with your GA tracking identifier

# Permalinks
permalink: /blog/:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

sass:
    style: compressed